// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://ducwbcjvmkxaqsglvhui.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR1Y3diY2p2bWt4YXFzZ2x2aHVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzE0ODY4NDQsImV4cCI6MjA0NzA2Mjg0NH0.tyT8rGWuDVdRmiowmlQjOck9HwlFCyyRQJ8a6qh979M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);